export const products = [
  {
    id: 'aria-headphones',
    name: 'Aria Wireless Headphones',
    category: 'Electronics',
    price: 24990,
    rating: 4.8,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'Noise-cancelling over-ear headphones with 30-hour battery life and a comfortable everyday fit.',
    info: ['Brand: Aria Audio', 'Battery: 30 hours', 'Connectivity: Bluetooth 5.3', 'Warranty: 1 year'],
    delivery: 'Standard delivery in 3–5 business days. Free shipping on orders above ₹499.',
    reviews: [
      { name: 'Ananya K.', rating: 5, date: '12 Aug 2026', comment: 'Excellent noise cancellation for commute and study sessions.' },
      { name: 'Rahul M.', rating: 4, date: '02 Aug 2026', comment: 'Comfortable for long wear. Bass is clean, not overpowering.' },
    ],
  },
  {
    id: 'pulse-smartwatch',
    name: 'Pulse Smartwatch SE',
    category: 'Electronics',
    price: 12990,
    rating: 4.6,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    description: 'Lightweight fitness watch with heart-rate tracking, GPS, and a bright always-on display.',
    info: ['Brand: Pulse', 'Water resistance: 5 ATM', 'GPS: Built-in', 'Warranty: 1 year'],
    delivery: 'Dispatched within 24 hours. Delivery in 2–4 business days.',
    reviews: [
      { name: 'Neha S.', rating: 5, date: '08 Aug 2026', comment: 'Accurate step count and a display that is easy to read outdoors.' },
      { name: 'Vikram P.', rating: 4, date: '28 Jul 2026', comment: 'Battery easily lasts four days with typical use.' },
    ],
  },
  {
    id: 'nova-earbuds',
    name: 'Nova True Wireless Earbuds',
    category: 'Electronics',
    price: 3999,
    rating: 4.4,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    description: 'Compact earbuds with a charging case, IPX4 splash resistance, and clear call quality.',
    info: ['Brand: Nova', 'Playtime: 6 + 18 hours', 'IP rating: IPX4', 'Warranty: 6 months'],
    delivery: 'Usually delivered in 3–5 business days.',
    reviews: [
      { name: 'Ishaan D.', rating: 4, date: '15 Aug 2026', comment: 'Solid everyday pair. Case is pocket-friendly.' },
      { name: 'Meera L.', rating: 5, date: '05 Aug 2026', comment: 'Calls are clearer than my previous earbuds.' },
    ],
  },
  {
    id: 'nova-speaker',
    name: 'Orbit Bluetooth Speaker',
    category: 'Electronics',
    price: 1899,
    rating: 4.3,
    stock: 'Low Stock',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
    description: 'Portable Bluetooth speaker with a full-range driver and 12-hour playtime for desks and small rooms.',
    info: ['Brand: Orbit', 'Playtime: 12 hours', 'Connectivity: Bluetooth 5.0', 'Warranty: 1 year'],
    delivery: 'Ships in 2 business days.',
    reviews: [
      { name: 'Kavya R.', rating: 4, date: '01 Aug 2026', comment: 'Good light for reading. Wish it had a warmer fourth mode.' },
    ],
  },
  {
    id: 'nordic-sneakers',
    name: 'Nordic Runner Sneakers',
    category: 'Fashion',
    price: 8495,
    rating: 4.7,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    description: 'Breathable everyday sneakers with cushioned soles, made for city walking and light workouts.',
    info: ['Brand: Nordic', 'Material: Mesh and rubber', 'Sizes: UK 6–11', 'Care: Wipe clean'],
    delivery: 'Delivery in 4–6 business days. Easy 7-day size exchange.',
    reviews: [
      { name: 'Aditya B.', rating: 5, date: '10 Aug 2026', comment: 'True to size and comfortable from the first wear.' },
      { name: 'Sana Q.', rating: 4, date: '22 Jul 2026', comment: 'Look premium. Slightly narrow in the toe box.' },
    ],
  },
  {
    id: 'aurel-overcoat',
    name: 'Aurel Wool Overcoat',
    category: 'Fashion',
    price: 6999,
    rating: 4.5,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80',
    description: 'Tailored wool-blend overcoat with a structured collar and a clean silhouette for daily wear.',
    info: ['Brand: Aurel', 'Material: Wool blend', 'Fit: Regular', 'Care: Dry clean'],
    delivery: 'Ships in 3 business days. Free returns within 7 days.',
    reviews: [
      { name: 'Rohit J.', rating: 5, date: '18 Jul 2026', comment: 'Good weight for Pune winters. Stitching looks neat.' },
    ],
  },
  {
    id: 'linen-shirt',
    name: 'Coastal Linen Shirt',
    category: 'Fashion',
    price: 1899,
    rating: 4.2,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1596755094514-f89e4a82c58f?auto=format&fit=crop&w=800&q=80',
    description: 'Breathable linen shirt with a relaxed collar, suited to warm weather and smart-casual outfits.',
    info: ['Brand: Coastal', 'Material: 100% linen', 'Fit: Relaxed', 'Care: Machine wash cold'],
    delivery: 'Usually delivered in 3–5 business days.',
    reviews: [
      { name: 'Priya N.', rating: 4, date: '09 Aug 2026', comment: 'Light fabric and a clean cut. Expect some natural wrinkles.' },
    ],
  },
  {
    id: 'leather-tote',
    name: 'Harbor Leather Tote',
    category: 'Fashion',
    price: 3299,
    rating: 4.6,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
    description: 'Everyday leather tote with an inner zip pocket and enough space for a 14-inch laptop sleeve.',
    info: ['Brand: Harbor', 'Material: Genuine leather', 'Laptop: Up to 14 inch', 'Warranty: 6 months'],
    delivery: 'Delivery in 4–6 business days.',
    reviews: [
      { name: 'Tanvi G.', rating: 5, date: '03 Aug 2026', comment: 'Holds my laptop and a water bottle without looking bulky.' },
    ],
  },
  {
    id: 'lumen-floor-lamp',
    name: 'Lumen Floor Lamp',
    category: 'Home & Living',
    price: 4799,
    rating: 4.4,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1507473885805-ee7489c0a5b7?auto=format&fit=crop&w=800&q=80',
    description: 'Minimal floor lamp with a warm LED bulb, linen shade, and a stable weighted base.',
    info: ['Brand: Lumen Home', 'Height: 150 cm', 'Bulb: Warm LED included', 'Warranty: 1 year'],
    delivery: 'Furniture-sized item. Delivery in 5–7 business days.',
    reviews: [
      { name: 'Arjun V.', rating: 4, date: '27 Jul 2026', comment: 'Warm light and a sturdy base. Assembly took ten minutes.' },
    ],
  },
  {
    id: 'haven-sofa',
    name: 'Haven Linen Sofa',
    category: 'Home & Living',
    price: 34990,
    rating: 4.9,
    stock: 'Low Stock',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    description: 'Three-seater linen sofa with deep cushions, solid wood legs, and a compact living-room footprint.',
    info: ['Brand: Haven', 'Seats: 3', 'Upholstery: Linen', 'Warranty: 2 years'],
    delivery: 'Scheduled delivery in 7–10 business days. Assembly available on request.',
    reviews: [
      { name: 'Sneha T.', rating: 5, date: '11 Aug 2026', comment: 'Comfortable seat depth and the fabric feels durable.' },
      { name: 'Dev K.', rating: 5, date: '30 Jul 2026', comment: 'Looks exactly like the photos. Worth the wait.' },
    ],
  },
  {
    id: 'ceramic-planter',
    name: 'Grove Ceramic Planter Set',
    category: 'Home & Living',
    price: 899,
    rating: 4.1,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80',
    description: 'Set of two matte ceramic planters with drainage holes, sized for indoor plants.',
    info: ['Brand: Grove', 'Set of: 2', 'Material: Ceramic', 'Indoor use recommended'],
    delivery: 'Delivered in 3–5 business days.',
    reviews: [
      { name: 'Nisha A.', rating: 4, date: '16 Aug 2026', comment: 'Simple design. Drainage works well with a saucer.' },
    ],
  },
  {
    id: 'cotton-duvet',
    name: 'Nimbus Cotton Duvet Cover',
    category: 'Home & Living',
    price: 2499,
    rating: 4.5,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
    description: 'Soft cotton duvet cover in a neutral weave, machine washable and sized for a queen bed.',
    info: ['Brand: Nimbus', 'Size: Queen', 'Material: 100% cotton', 'Care: Machine wash'],
    delivery: 'Usually delivered in 4–6 business days.',
    reviews: [
      { name: 'Farhan I.', rating: 5, date: '06 Aug 2026', comment: 'Breathable in summer. Colour matches the listing.' },
    ],
  },
  {
    id: 'marketplace-mindset',
    name: 'The Marketplace Mindset',
    category: 'Books',
    price: 499,
    rating: 4.6,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80',
    description: 'A practical hardcover on building customer-first brands, with case studies from modern retail.',
    info: ['Format: Hardcover', 'Pages: 284', 'Language: English', 'Publisher: Northline Press'],
    delivery: 'Books ship within 24 hours. Delivery in 2–4 business days.',
    reviews: [
      { name: 'Pooja H.', rating: 5, date: '14 Aug 2026', comment: 'Clear examples. Useful for a college project on retail UX.' },
      { name: 'Amit S.', rating: 4, date: '20 Jul 2026', comment: 'Good overview. A few chapters repeat the same idea.' },
    ],
  },
  {
    id: 'javascript-patterns',
    name: 'Practical JavaScript Patterns',
    category: 'Books',
    price: 799,
    rating: 4.7,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    description: 'A student-friendly guide to writing cleaner vanilla JavaScript for real web interfaces.',
    info: ['Format: Paperback', 'Pages: 312', 'Language: English', 'Level: Intermediate'],
    delivery: 'Dispatched the same day for orders before 5 PM.',
    reviews: [
      { name: 'Ritika M.', rating: 5, date: '04 Aug 2026', comment: 'Explains modules and DOM patterns without extra frameworks.' },
    ],
  },
  {
    id: 'home-cooking',
    name: 'Weeknight Home Cooking',
    category: 'Books',
    price: 650,
    rating: 4.3,
    stock: 'Out of Stock',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    description: 'Forty simple recipes designed for busy evenings, with pantry-friendly ingredients.',
    info: ['Format: Paperback', 'Pages: 196', 'Language: English', 'Includes: Metric measures'],
    delivery: 'Currently unavailable. Restock expected next week.',
    reviews: [
      { name: 'Leela C.', rating: 4, date: '12 Jul 2026', comment: 'Recipes are realistic. Hoping it comes back in stock soon.' },
    ],
  },
  {
    id: 'yoga-mat-pro',
    name: 'Forge Yoga Mat Pro',
    category: 'Sports',
    price: 1299,
    rating: 4.7,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
    description: 'Non-slip 6mm yoga mat with alignment marks, easy to roll, and suitable for home or studio sessions.',
    info: ['Brand: Forge', 'Thickness: 6 mm', 'Material: TPE', 'Includes: Carry strap'],
    delivery: 'Delivery in 3–5 business days.',
    reviews: [
      { name: 'Kiran W.', rating: 5, date: '17 Aug 2026', comment: 'Grips well even during vinyasa. No chemical smell.' },
      { name: 'Aisha F.', rating: 4, date: '29 Jul 2026', comment: 'Good thickness. Alignment marks are helpful.' },
    ],
  },
  {
    id: 'steel-bottle',
    name: 'Trail Stainless Bottle 1L',
    category: 'Sports',
    price: 899,
    rating: 4.4,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    description: 'Insulated 1 litre steel bottle that keeps water cold during workouts and outdoor travel.',
    info: ['Brand: Trail', 'Capacity: 1 L', 'Insulation: Double wall', 'BPA-free lid'],
    delivery: 'Usually delivered in 3–5 business days.',
    reviews: [
      { name: 'Harsh P.', rating: 4, date: '07 Aug 2026', comment: 'Keeps water cold through a gym session. Lid is leak-proof.' },
    ],
  },
  {
    id: 'jump-rope',
    name: 'Forge Speed Jump Rope',
    category: 'Sports',
    price: 549,
    rating: 4.2,
    stock: 'In Stock',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80',
    description: 'Adjustable speed rope with comfortable handles for cardio warm-ups at home.',
    info: ['Brand: Forge', 'Length: Adjustable', 'Handles: Cushioned', 'Use: Indoor / outdoor'],
    delivery: 'Ships within 24 hours.',
    reviews: [
      { name: 'Yash R.', rating: 4, date: '13 Aug 2026', comment: 'Light and easy to adjust. Good value for beginners.' },
    ],
  },
]

export const categories = ['All', 'Electronics', 'Fashion', 'Home & Living', 'Books', 'Sports']

export function getProductById(id) {
  return products.find((product) => product.id === id)
}
